title: LLM Engineering Essentials Knowledge Base
description: Supporting materials for the LLM Engineering Essentials course by Nebius Academy
theme: minima
permalink: /:title/
baseurl: "/knowledge-base"
